export const mockGeneralLedger = {
  object_category: "general-ledger",
  connection_id: "2d5bb9be-a096-4fb3-9c97-83e1c64f839e",
  user: "2d5bb9be-b096-4fa3-9c97-83e1c64f839e",
  object_creation_date: "2024-12-08T03:52:40.439Z",
  data: [
    {
      account_category: "revenue",
      account_code: "200",
      account_currency: "AUD",
      account_identifier: "2d5bb9be-a096-4fa6-9c97-83e1c64f839e",
      account_status: "ACTIVE",
      value_type: "credit",
      account_name: "Sales",
      account_type: "sales",
      account_type_bank: "",
      system_account: "",
      total_value: 25321.28,
    },
    {
      account_category: "revenue",
      account_code: "200",
      account_currency: "AUD",
      account_identifier: "2d5bb9f2-a096-4fa6-9c97-83e1c64f839e",
      account_status: "ACTIVE",
      value_type: "debit",
      account_name: "Sales Refund",
      account_type: "sales",
      account_type_bank: "",
      system_account: "",
      total_value: 5606.5,
    },
    {
      account_category: "expense",
      account_code: "400",
      account_currency: "AUD",
      account_identifier: "2d5bb9be-a096-4fa3-9c97-83e1d64f839e",
      account_name: "Advertising",
      account_status: "ACTIVE",
      account_type: "overheads",
      account_type_bank: "",
      system_account: "",
      value_type: "debit",
      total_value: 1289.58,
    },
    {
      account_category: "liability",
      account_code: "800",
      account_currency: "AUD",
      account_identifier: "8e9c5122-d3fe-4e21-827a-f42753568e80",
      account_name: "Accounts Payable",
      account_status: "ACTIVE",
      account_type: "current_accounts_payable",
      account_type_bank: "",
      system_account: "CREDITORS",
      value_type: "credit",
      total_value: 2000,
    },
    {
      account_category: "assets",
      account_code: "710",
      account_currency: "AUD",
      account_identifier: "2d69b4ee-37d4-4f67-b950-32cbdd5765ed",
      account_name: "Office Equipment",
      account_status: "ACTIVE",
      account_type: "fixed",
      account_type_bank: "",
      system_account: "",
      value_type: "debit",
      total_value: 750.0,
    },
    {
      account_category: "assets",
      account_code: "711",
      account_currency: "AUD",
      account_identifier: "24d010bf-5e4b-42dd-9aa3-a5484dd0686f",
      account_name: "Accumulated Depreciation",
      account_status: "ACTIVE",
      account_type: "fixed",
      account_type_bank: "",
      system_account: "",
      value_type: "credit",
      total_value: 825.0,
    },
  ],
  currency: "AUD",
  object_origin_type: "accounting",
  object_origin_category: "bookkeeping",
  object_type: "day",
  object_class: "timeline-balance",
  balance_date: "2020-09-30T00:00:00.000Z",
};

export const camelCaseMockGeneralLedger = {
  objectCategory: "general-ledger",
  connectionId: "2d5bb9be-a096-4fb3-9c97-83e1c64f839e",
  user: "2d5bb9be-b096-4fa3-9c97-83e1c64f839e",
  objectCreationDate: "2024-12-08T03:52:40.439Z",
  data: [
    {
      accountCategory: "revenue",
      accountCode: "200",
      accountCurrency: "AUD",
      accountIdentifier: "2d5bb9be-a096-4fa6-9c97-83e1c64f839e",
      accountStatus: "ACTIVE",
      valueType: "credit",
      accountName: "Sales",
      accountType: "sales",
      accountTypeBank: "",
      systemAccount: "",
      totalValue: 25321.28,
    },
    {
      accountCategory: "revenue",
      accountCode: "200",
      accountCurrency: "AUD",
      accountIdentifier: "2d5bb9f2-a096-4fa6-9c97-83e1c64f839e",
      accountStatus: "ACTIVE",
      valueType: "debit",
      accountName: "Sales Refund",
      accountType: "sales",
      accountTypeBank: "",
      systemAccount: "",
      totalValue: 5606.5,
    },
    {
      accountCategory: "expense",
      accountCode: "400",
      accountCurrency: "AUD",
      accountIdentifier: "2d5bb9be-a096-4fa3-9c97-83e1d64f839e",
      accountName: "Advertising",
      accountStatus: "ACTIVE",
      accountType: "overheads",
      accountTypeBank: "",
      systemAccount: "",
      valueType: "debit",
      totalValue: 1289.58,
    },
    {
      accountCategory: "liability",
      accountCode: "800",
      accountCurrency: "AUD",
      accountIdentifier: "8e9c5122-d3fe-4e21-827a-f42753568e80",
      accountName: "Accounts Payable",
      accountStatus: "ACTIVE",
      accountType: "current_accounts_payable",
      accountTypeBank: "",
      systemAccount: "CREDITORS",
      valueType: "credit",
      totalValue: 2000,
    },
    {
      accountCategory: "assets",
      accountCode: "710",
      accountCurrency: "AUD",
      accountIdentifier: "2d69b4ee-37d4-4f67-b950-32cbdd5765ed",
      accountName: "Office Equipment",
      accountStatus: "ACTIVE",
      accountType: "fixed",
      accountTypeBank: "",
      systemAccount: "",
      valueType: "debit",
      totalValue: 750.0,
    },
    {
      accountCategory: "assets",
      accountCode: "711",
      accountCurrency: "AUD",
      accountIdentifier: "24d010bf-5e4b-42dd-9aa3-a5484dd0686f",
      accountName: "Accumulated Depreciation",
      accountStatus: "ACTIVE",
      accountType: "fixed",
      accountTypeBank: "",
      systemAccount: "",
      valueType: "credit",
      totalValue: 825.0,
    },
  ],
  currency: "AUD",
  objectOriginType: "accounting",
  objectOriginCategory: "bookkeeping",
  objectType: "day",
  objectClass: "timeline-balance",
  balanceDate: "2020-09-30T00:00:00.000Z",
};
