export const mockGeneralLedger = {
  object_category: "general-ledger",
  connection_id: "2d5bb9be-a096-4fb3-9c97-83e1c64f839e",
  user: "2d5bb9be-b096-4fa3-9c97-83e1c64f839e",
  object_creation_date: "2024-12-08T03:52:40.439Z",
  data: [
    {
      account_category: "revenue",
      account_code: "200",
      account_currency: "AUD",
      account_identifier: "2d5bb9be-a096-4fa6-9c97-83e1c64f839e",
      account_status: "ACTIVE",
      value_type: "credit",
      account_name: "Sales",
      account_type: "sales",
      account_type_bank: "",
      system_account: "",
      total_value: 25321.28,
    },
    {
      account_category: "revenue",
      account_code: "200",
      account_currency: "AUD",
      account_identifier: "2d5bb9f2-a096-4fa6-9c97-83e1c64f839e",
      account_status: "ACTIVE",
      value_type: "debit",
      account_name: "Sales",
      account_type: "sales",
      account_type_bank: "",
      system_account: "",
      total_value: 5606.5,
    },
    {
      account_code: "400",
      account_currency: "AUD",
      account_identifier: "2d5bb9be-a096-4fa3-9c97-83e1d64f839e",
      account_name: "Advertising",
      account_status: "ACTIVE",
      system_account: "",
      value_type: "debit",
      account_category: "expense",
      account_type_bank: "",
      total_value: 1289.58,
      account_type: "overheads",
    },
    {
      account_category: "expense",
      account_code: "408",
      account_currency: "AUD",
      account_identifier: "ff09eac3-5b17-44fb-9eea-e2e9375e91b4",
      account_name: "Cleaning",
      account_status: "ACTIVE",
      account_type: "overheads",
      account_type_bank: "",
      system_account: "",
      value_type: "debit",
      total_value: 620.5,
    },
    {
      account_category: "expense",
      account_code: "412",
      account_currency: "AUD",
      account_identifier: "6db51cfa-0326-4e63-a743-c78c4d99aba4",
      account_name: "Consulting & Accounting",
      account_status: "ACTIVE",
      account_type: "overheads",
      account_type_bank: "",
      system_account: "",
      value_type: "debit",
      total_value: 35.9,
    },
    {
      account_category: "expense",
      account_code: "420",
      account_currency: "AUD",
      account_identifier: "18e27517-81e0-437c-bc21-fbba8e30d6bb",
      account_name: "Entertainment",
      account_status: "ACTIVE",
      account_type: "overheads",
      account_type_bank: "",
      system_account: "",
      value_type: "debit",
      total_value: 102.5,
    },
  ],
  currency: "AUD",
  object_origin_type: "accounting",
  object_origin_category: "bookkeeping",
  object_type: "day",
  object_class: "timeline-balance",
  balance_date: "2020-09-30T00:00:00.000Z",
};

export const camelCaseMockGeneralLedger = {
  objectCategory: "general-ledger",
  connectionId: "2d5bb9be-a096-4fb3-9c97-83e1c64f839e",
  user: "2d5bb9be-b096-4fa3-9c97-83e1c64f839e",
  objectCreationDate: "2024-12-08T03:52:40.439Z",
  data: [
    {
      accountCategory: "revenue",
      accountCode: "200",
      accountCurrency: "AUD",
      accountIdentifier: "2d5bb9be-a096-4fa6-9c97-83e1c64f839e",
      accountStatus: "ACTIVE",
      valueType: "credit",
      accountName: "Sales",
      accountType: "sales",
      accountTypeBank: "",
      systemAccount: "",
      totalValue: 25321.28,
    },
    {
      accountCategory: "revenue",
      accountCode: "200",
      accountCurrency: "AUD",
      accountIdentifier: "2d5bb9f2-a096-4fa6-9c97-83e1c64f839e",
      accountStatus: "ACTIVE",
      valueType: "debit",
      accountName: "Sales",
      accountType: "sales",
      accountTypeBank: "",
      systemAccount: "",
      totalValue: 5606.5,
    },
    {
      accountCategory: "expense",
      accountCode: "400",
      accountCurrency: "AUD",
      accountIdentifier: "2d5bb9be-a096-4fa3-9c97-83e1d64f839e",
      accountName: "Advertising",
      accountStatus: "ACTIVE",
      accountType: "overheads",
      accountTypeBank: "",
      systemAccount: "",
      valueType: "debit",
      totalValue: 1289.58,
    },
    {
      accountCategory: "expense",
      accountCode: "408",
      accountCurrency: "AUD",
      accountIdentifier: "ff09eac3-5b17-44fb-9eea-e2e9375e91b4",
      accountName: "Cleaning",
      accountStatus: "ACTIVE",
      accountType: "overheads",
      accountTypeBank: "",
      systemAccount: "",
      valueType: "debit",
      totalValue: 620.5,
    },
    {
      accountCategory: "expense",
      accountCode: "412",
      accountCurrency: "AUD",
      accountIdentifier: "6db51cfa-0326-4e63-a743-c78c4d99aba4",
      accountName: "Consulting & Accounting",
      accountStatus: "ACTIVE",
      accountType: "overheads",
      accountTypeBank: "",
      systemAccount: "",
      valueType: "debit",
      totalValue: 35.9,
    },
    {
      accountCategory: "expense",
      accountCode: "420",
      accountCurrency: "AUD",
      accountIdentifier: "18e27517-81e0-437c-bc21-fbba8e30d6bb",
      accountName: "Entertainment",
      accountStatus: "ACTIVE",
      accountType: "overheads",
      accountTypeBank: "",
      systemAccount: "",
      valueType: "debit",
      totalValue: 102.5,
    },
  ],
  currency: "AUD",
  objectOriginType: "accounting",
  objectOriginCategory: "bookkeeping",
  objectType: "day",
  objectClass: "timeline-balance",
  balanceDate: "2020-09-30T00:00:00.000Z",
};
