name: RewardPay-Coding-Challenge Test and Build Workflow

on:
  push:
    branches:
      - main
      - feature/accounting-metrics
  pull_request:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image with logs
        run: |
          docker build -t rewardpay-coding-challenge . | tee test-logs.txt

      - name: Upload test logs
        uses: actions/upload-artifact@v3
        with:
          name: test-logs
          path: test-logs.txt
